=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.22.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class CreateProjectDraftRequest < ApiModelBase
    # Public HTTP(S) URL with a DNS hostname or public IP address. Credentials, private and special IP addresses, localhost and internal hostnames are rejected.
    attr_accessor :website_url

    attr_accessor :main_country

    attr_accessor :main_language

    attr_accessor :use_subdomain

    attr_accessor :suggest

    attr_accessor :execute_prompts_immediately

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'website_url' => :'website_url',
        :'main_country' => :'main_country',
        :'main_language' => :'main_language',
        :'use_subdomain' => :'use_subdomain',
        :'suggest' => :'suggest',
        :'execute_prompts_immediately' => :'execute_prompts_immediately'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'website_url' => :'String',
        :'main_country' => :'String',
        :'main_language' => :'String',
        :'use_subdomain' => :'Boolean',
        :'suggest' => :'Boolean',
        :'execute_prompts_immediately' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::CreateProjectDraftRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::CreateProjectDraftRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'website_url')
        self.website_url = attributes[:'website_url']
      else
        self.website_url = nil
      end

      if attributes.key?(:'main_country')
        self.main_country = attributes[:'main_country']
      else
        self.main_country = nil
      end

      if attributes.key?(:'main_language')
        self.main_language = attributes[:'main_language']
      else
        self.main_language = nil
      end

      if attributes.key?(:'use_subdomain')
        self.use_subdomain = attributes[:'use_subdomain']
      else
        self.use_subdomain = false
      end

      if attributes.key?(:'suggest')
        self.suggest = attributes[:'suggest']
      else
        self.suggest = true
      end

      if attributes.key?(:'execute_prompts_immediately')
        self.execute_prompts_immediately = attributes[:'execute_prompts_immediately']
      else
        self.execute_prompts_immediately = true
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @website_url.nil?
        invalid_properties.push('invalid value for "website_url", website_url cannot be nil.')
      end

      if @main_country.nil?
        invalid_properties.push('invalid value for "main_country", main_country cannot be nil.')
      end

      if @main_language.nil?
        invalid_properties.push('invalid value for "main_language", main_language cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @website_url.nil?
      return false if @main_country.nil?
      return false if @main_language.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] website_url Value to be assigned
    def website_url=(website_url)
      if website_url.nil?
        fail ArgumentError, 'website_url cannot be nil'
      end

      @website_url = website_url
    end

    # Custom attribute writer method with validation
    # @param [Object] main_country Value to be assigned
    def main_country=(main_country)
      if main_country.nil?
        fail ArgumentError, 'main_country cannot be nil'
      end

      @main_country = main_country
    end

    # Custom attribute writer method with validation
    # @param [Object] main_language Value to be assigned
    def main_language=(main_language)
      if main_language.nil?
        fail ArgumentError, 'main_language cannot be nil'
      end

      @main_language = main_language
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          website_url == o.website_url &&
          main_country == o.main_country &&
          main_language == o.main_language &&
          use_subdomain == o.use_subdomain &&
          suggest == o.suggest &&
          execute_prompts_immediately == o.execute_prompts_immediately
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [website_url, main_country, main_language, use_subdomain, suggest, execute_prompts_immediately].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
