=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.57.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class GeoAuditResponse < ApiModelBase
    # Stable audit id
    attr_accessor :id

    attr_accessor :audit_type

    # The audited domain (site-wide types) or page URL, normalized
    attr_accessor :target

    attr_accessor :country_code

    attr_accessor :cadence

    attr_accessor :status

    # user, or unreachable when three runs in a row could not reach the site
    attr_accessor :paused_reason

    attr_accessor :schedule

    attr_accessor :next_run_at

    attr_accessor :email_alerts

    # Whether this audit type can run weekly or monthly
    attr_accessor :recurring_available

    # Whether runs of this type produce findings and issues, or a score only
    attr_accessor :checks_tracked

    attr_accessor :latest_run

    attr_accessor :open_issues

    attr_accessor :open_critical_issues

    attr_accessor :created_at

    attr_accessor :app_url

    attr_accessor :project_id

    attr_accessor :request_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'audit_type' => :'audit_type',
        :'target' => :'target',
        :'country_code' => :'country_code',
        :'cadence' => :'cadence',
        :'status' => :'status',
        :'paused_reason' => :'paused_reason',
        :'schedule' => :'schedule',
        :'next_run_at' => :'next_run_at',
        :'email_alerts' => :'email_alerts',
        :'recurring_available' => :'recurring_available',
        :'checks_tracked' => :'checks_tracked',
        :'latest_run' => :'latest_run',
        :'open_issues' => :'open_issues',
        :'open_critical_issues' => :'open_critical_issues',
        :'created_at' => :'created_at',
        :'app_url' => :'app_url',
        :'project_id' => :'project_id',
        :'request_id' => :'request_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'audit_type' => :'String',
        :'target' => :'String',
        :'country_code' => :'String',
        :'cadence' => :'String',
        :'status' => :'String',
        :'paused_reason' => :'String',
        :'schedule' => :'GeoAuditSchedule',
        :'next_run_at' => :'Time',
        :'email_alerts' => :'Boolean',
        :'recurring_available' => :'Boolean',
        :'checks_tracked' => :'Boolean',
        :'latest_run' => :'GeoAuditRun',
        :'open_issues' => :'Integer',
        :'open_critical_issues' => :'Integer',
        :'created_at' => :'Time',
        :'app_url' => :'String',
        :'project_id' => :'Integer',
        :'request_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'country_code',
        :'paused_reason',
        :'schedule',
        :'next_run_at',
        :'latest_run',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'GeoAudit'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::GeoAuditResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::GeoAuditResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'audit_type')
        self.audit_type = attributes[:'audit_type']
      end

      if attributes.key?(:'target')
        self.target = attributes[:'target']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      end

      if attributes.key?(:'cadence')
        self.cadence = attributes[:'cadence']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'paused_reason')
        self.paused_reason = attributes[:'paused_reason']
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'next_run_at')
        self.next_run_at = attributes[:'next_run_at']
      end

      if attributes.key?(:'email_alerts')
        self.email_alerts = attributes[:'email_alerts']
      end

      if attributes.key?(:'recurring_available')
        self.recurring_available = attributes[:'recurring_available']
      end

      if attributes.key?(:'checks_tracked')
        self.checks_tracked = attributes[:'checks_tracked']
      end

      if attributes.key?(:'latest_run')
        self.latest_run = attributes[:'latest_run']
      end

      if attributes.key?(:'open_issues')
        self.open_issues = attributes[:'open_issues']
      end

      if attributes.key?(:'open_critical_issues')
        self.open_critical_issues = attributes[:'open_critical_issues']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'app_url')
        self.app_url = attributes[:'app_url']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      audit_type_validator = EnumAttributeValidator.new('String', ["agent_readiness", "robots_txt", "crawlability", "schema", "content_readiness", "discoverability", "site_structure"])
      return false unless audit_type_validator.valid?(@audit_type)
      cadence_validator = EnumAttributeValidator.new('String', ["once", "weekly", "monthly"])
      return false unless cadence_validator.valid?(@cadence)
      status_validator = EnumAttributeValidator.new('String', ["active", "paused", "archived"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] audit_type Object to be assigned
    def audit_type=(audit_type)
      validator = EnumAttributeValidator.new('String', ["agent_readiness", "robots_txt", "crawlability", "schema", "content_readiness", "discoverability", "site_structure"])
      unless validator.valid?(audit_type)
        fail ArgumentError, "invalid value for \"audit_type\", must be one of #{validator.allowable_values}."
      end
      @audit_type = audit_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cadence Object to be assigned
    def cadence=(cadence)
      validator = EnumAttributeValidator.new('String', ["once", "weekly", "monthly"])
      unless validator.valid?(cadence)
        fail ArgumentError, "invalid value for \"cadence\", must be one of #{validator.allowable_values}."
      end
      @cadence = cadence
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["active", "paused", "archived"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          audit_type == o.audit_type &&
          target == o.target &&
          country_code == o.country_code &&
          cadence == o.cadence &&
          status == o.status &&
          paused_reason == o.paused_reason &&
          schedule == o.schedule &&
          next_run_at == o.next_run_at &&
          email_alerts == o.email_alerts &&
          recurring_available == o.recurring_available &&
          checks_tracked == o.checks_tracked &&
          latest_run == o.latest_run &&
          open_issues == o.open_issues &&
          open_critical_issues == o.open_critical_issues &&
          created_at == o.created_at &&
          app_url == o.app_url &&
          project_id == o.project_id &&
          request_id == o.request_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, audit_type, target, country_code, cadence, status, paused_reason, schedule, next_run_at, email_alerts, recurring_available, checks_tracked, latest_run, open_issues, open_critical_issues, created_at, app_url, project_id, request_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
