=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.56.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class GeoAuditRunResponse < ApiModelBase
    # Run number within the audit, starting at 1
    attr_accessor :sequence

    attr_accessor :status

    attr_accessor :trigger

    attr_accessor :score

    attr_accessor :grade

    # Score change against the previous completed run
    attr_accessor :score_delta

    # False when the checks or the audit settings changed since the previous run, so a diff may reflect that change
    attr_accessor :comparable_to_previous

    attr_accessor :new_issues

    attr_accessor :fixed_issues

    attr_accessor :regressed_issues

    attr_accessor :error

    attr_accessor :engine_version

    attr_accessor :created_at

    attr_accessor :finished_at

    attr_accessor :app_url

    attr_accessor :project_id

    attr_accessor :request_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sequence' => :'sequence',
        :'status' => :'status',
        :'trigger' => :'trigger',
        :'score' => :'score',
        :'grade' => :'grade',
        :'score_delta' => :'score_delta',
        :'comparable_to_previous' => :'comparable_to_previous',
        :'new_issues' => :'new_issues',
        :'fixed_issues' => :'fixed_issues',
        :'regressed_issues' => :'regressed_issues',
        :'error' => :'error',
        :'engine_version' => :'engine_version',
        :'created_at' => :'created_at',
        :'finished_at' => :'finished_at',
        :'app_url' => :'app_url',
        :'project_id' => :'project_id',
        :'request_id' => :'request_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sequence' => :'Integer',
        :'status' => :'String',
        :'trigger' => :'String',
        :'score' => :'Float',
        :'grade' => :'String',
        :'score_delta' => :'Float',
        :'comparable_to_previous' => :'Boolean',
        :'new_issues' => :'Integer',
        :'fixed_issues' => :'Integer',
        :'regressed_issues' => :'Integer',
        :'error' => :'String',
        :'engine_version' => :'String',
        :'created_at' => :'Time',
        :'finished_at' => :'Time',
        :'app_url' => :'String',
        :'project_id' => :'Integer',
        :'request_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'score',
        :'grade',
        :'score_delta',
        :'error',
        :'engine_version',
        :'finished_at',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'GeoAuditRun'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::GeoAuditRunResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::GeoAuditRunResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sequence')
        self.sequence = attributes[:'sequence']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'trigger')
        self.trigger = attributes[:'trigger']
      end

      if attributes.key?(:'score')
        self.score = attributes[:'score']
      end

      if attributes.key?(:'grade')
        self.grade = attributes[:'grade']
      end

      if attributes.key?(:'score_delta')
        self.score_delta = attributes[:'score_delta']
      end

      if attributes.key?(:'comparable_to_previous')
        self.comparable_to_previous = attributes[:'comparable_to_previous']
      end

      if attributes.key?(:'new_issues')
        self.new_issues = attributes[:'new_issues']
      end

      if attributes.key?(:'fixed_issues')
        self.fixed_issues = attributes[:'fixed_issues']
      end

      if attributes.key?(:'regressed_issues')
        self.regressed_issues = attributes[:'regressed_issues']
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      end

      if attributes.key?(:'engine_version')
        self.engine_version = attributes[:'engine_version']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'finished_at')
        self.finished_at = attributes[:'finished_at']
      end

      if attributes.key?(:'app_url')
        self.app_url = attributes[:'app_url']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      status_validator = EnumAttributeValidator.new('String', ["queued", "running", "completed", "failed", "unreachable"])
      return false unless status_validator.valid?(@status)
      trigger_validator = EnumAttributeValidator.new('String', ["scheduled", "manual", "api", "mcp", "legacy_import"])
      return false unless trigger_validator.valid?(@trigger)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["queued", "running", "completed", "failed", "unreachable"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] trigger Object to be assigned
    def trigger=(trigger)
      validator = EnumAttributeValidator.new('String', ["scheduled", "manual", "api", "mcp", "legacy_import"])
      unless validator.valid?(trigger)
        fail ArgumentError, "invalid value for \"trigger\", must be one of #{validator.allowable_values}."
      end
      @trigger = trigger
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sequence == o.sequence &&
          status == o.status &&
          trigger == o.trigger &&
          score == o.score &&
          grade == o.grade &&
          score_delta == o.score_delta &&
          comparable_to_previous == o.comparable_to_previous &&
          new_issues == o.new_issues &&
          fixed_issues == o.fixed_issues &&
          regressed_issues == o.regressed_issues &&
          error == o.error &&
          engine_version == o.engine_version &&
          created_at == o.created_at &&
          finished_at == o.finished_at &&
          app_url == o.app_url &&
          project_id == o.project_id &&
          request_id == o.request_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sequence, status, trigger, score, grade, score_delta, comparable_to_previous, new_issues, fixed_issues, regressed_issues, error, engine_version, created_at, finished_at, app_url, project_id, request_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
