=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.48.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class IntelligenceTaskUpdateResponse < ApiModelBase
    attr_accessor :id

    attr_accessor :public_id

    attr_accessor :project_id

    attr_accessor :task_type

    attr_accessor :title

    attr_accessor :status

    attr_accessor :prompt_id

    attr_accessor :prompt_text

    attr_accessor :agentic_mode

    attr_accessor :custom_topic

    attr_accessor :user_instructions

    attr_accessor :output_language_code

    attr_accessor :word_count

    # Only present when status='completed'
    attr_accessor :result_data

    attr_accessor :error_message

    attr_accessor :estimated_time

    attr_accessor :created_at

    attr_accessor :processed_at

    # When the content was last edited by hand; null while the output is as generated
    attr_accessor :manually_edited_at

    # User behind the last manual edit; null for an unedited task or an edit made from an embedded portal
    attr_accessor :edited_by_user_id

    attr_accessor :request_id

    # Paths whose text actually changed; empty when every value matched the stored text
    attr_accessor :changed_paths

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'public_id' => :'public_id',
        :'project_id' => :'project_id',
        :'task_type' => :'task_type',
        :'title' => :'title',
        :'status' => :'status',
        :'prompt_id' => :'prompt_id',
        :'prompt_text' => :'prompt_text',
        :'agentic_mode' => :'agentic_mode',
        :'custom_topic' => :'custom_topic',
        :'user_instructions' => :'user_instructions',
        :'output_language_code' => :'output_language_code',
        :'word_count' => :'word_count',
        :'result_data' => :'result_data',
        :'error_message' => :'error_message',
        :'estimated_time' => :'estimated_time',
        :'created_at' => :'created_at',
        :'processed_at' => :'processed_at',
        :'manually_edited_at' => :'manually_edited_at',
        :'edited_by_user_id' => :'edited_by_user_id',
        :'request_id' => :'request_id',
        :'changed_paths' => :'changed_paths'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'public_id' => :'String',
        :'project_id' => :'Integer',
        :'task_type' => :'String',
        :'title' => :'String',
        :'status' => :'String',
        :'prompt_id' => :'Integer',
        :'prompt_text' => :'String',
        :'agentic_mode' => :'Boolean',
        :'custom_topic' => :'String',
        :'user_instructions' => :'String',
        :'output_language_code' => :'String',
        :'word_count' => :'Integer',
        :'result_data' => :'Object',
        :'error_message' => :'String',
        :'estimated_time' => :'String',
        :'created_at' => :'Time',
        :'processed_at' => :'Time',
        :'manually_edited_at' => :'Time',
        :'edited_by_user_id' => :'Integer',
        :'request_id' => :'String',
        :'changed_paths' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'prompt_id',
        :'prompt_text',
        :'custom_topic',
        :'user_instructions',
        :'output_language_code',
        :'word_count',
        :'error_message',
        :'estimated_time',
        :'processed_at',
        :'manually_edited_at',
        :'edited_by_user_id',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'IntelligenceTask'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::IntelligenceTaskUpdateResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::IntelligenceTaskUpdateResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'public_id')
        self.public_id = attributes[:'public_id']
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'task_type')
        self.task_type = attributes[:'task_type']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'prompt_id')
        self.prompt_id = attributes[:'prompt_id']
      end

      if attributes.key?(:'prompt_text')
        self.prompt_text = attributes[:'prompt_text']
      end

      if attributes.key?(:'agentic_mode')
        self.agentic_mode = attributes[:'agentic_mode']
      end

      if attributes.key?(:'custom_topic')
        self.custom_topic = attributes[:'custom_topic']
      end

      if attributes.key?(:'user_instructions')
        self.user_instructions = attributes[:'user_instructions']
      end

      if attributes.key?(:'output_language_code')
        self.output_language_code = attributes[:'output_language_code']
      end

      if attributes.key?(:'word_count')
        self.word_count = attributes[:'word_count']
      end

      if attributes.key?(:'result_data')
        self.result_data = attributes[:'result_data']
      end

      if attributes.key?(:'error_message')
        self.error_message = attributes[:'error_message']
      end

      if attributes.key?(:'estimated_time')
        self.estimated_time = attributes[:'estimated_time']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'processed_at')
        self.processed_at = attributes[:'processed_at']
      end

      if attributes.key?(:'manually_edited_at')
        self.manually_edited_at = attributes[:'manually_edited_at']
      end

      if attributes.key?(:'edited_by_user_id')
        self.edited_by_user_id = attributes[:'edited_by_user_id']
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      end

      if attributes.key?(:'changed_paths')
        if (value = attributes[:'changed_paths']).is_a?(Array)
          self.changed_paths = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          public_id == o.public_id &&
          project_id == o.project_id &&
          task_type == o.task_type &&
          title == o.title &&
          status == o.status &&
          prompt_id == o.prompt_id &&
          prompt_text == o.prompt_text &&
          agentic_mode == o.agentic_mode &&
          custom_topic == o.custom_topic &&
          user_instructions == o.user_instructions &&
          output_language_code == o.output_language_code &&
          word_count == o.word_count &&
          result_data == o.result_data &&
          error_message == o.error_message &&
          estimated_time == o.estimated_time &&
          created_at == o.created_at &&
          processed_at == o.processed_at &&
          manually_edited_at == o.manually_edited_at &&
          edited_by_user_id == o.edited_by_user_id &&
          request_id == o.request_id &&
          changed_paths == o.changed_paths
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, public_id, project_id, task_type, title, status, prompt_id, prompt_text, agentic_mode, custom_topic, user_instructions, output_language_code, word_count, result_data, error_message, estimated_time, created_at, processed_at, manually_edited_at, edited_by_user_id, request_id, changed_paths].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
