=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.22.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class IntelligenceTaskCreateRequest < ApiModelBase
    attr_accessor :project_id

    attr_accessor :task_type

    attr_accessor :prompt_id

    attr_accessor :custom_topic

    attr_accessor :user_instructions

    attr_accessor :output_language_code

    attr_accessor :existing_content

    attr_accessor :existing_content_url

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'project_id' => :'project_id',
        :'task_type' => :'task_type',
        :'prompt_id' => :'prompt_id',
        :'custom_topic' => :'custom_topic',
        :'user_instructions' => :'user_instructions',
        :'output_language_code' => :'output_language_code',
        :'existing_content' => :'existing_content',
        :'existing_content_url' => :'existing_content_url'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'project_id' => :'Integer',
        :'task_type' => :'String',
        :'prompt_id' => :'Integer',
        :'custom_topic' => :'String',
        :'user_instructions' => :'String',
        :'output_language_code' => :'String',
        :'existing_content' => :'String',
        :'existing_content_url' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::IntelligenceTaskCreateRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::IntelligenceTaskCreateRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      else
        self.project_id = nil
      end

      if attributes.key?(:'task_type')
        self.task_type = attributes[:'task_type']
      else
        self.task_type = nil
      end

      if attributes.key?(:'prompt_id')
        self.prompt_id = attributes[:'prompt_id']
      end

      if attributes.key?(:'custom_topic')
        self.custom_topic = attributes[:'custom_topic']
      end

      if attributes.key?(:'user_instructions')
        self.user_instructions = attributes[:'user_instructions']
      end

      if attributes.key?(:'output_language_code')
        self.output_language_code = attributes[:'output_language_code']
      end

      if attributes.key?(:'existing_content')
        self.existing_content = attributes[:'existing_content']
      end

      if attributes.key?(:'existing_content_url')
        self.existing_content_url = attributes[:'existing_content_url']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @project_id.nil?
        invalid_properties.push('invalid value for "project_id", project_id cannot be nil.')
      end

      if @task_type.nil?
        invalid_properties.push('invalid value for "task_type", task_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @project_id.nil?
      return false if @task_type.nil?
      task_type_validator = EnumAttributeValidator.new('String', ["brief", "create", "update", "pr_insights", "custom"])
      return false unless task_type_validator.valid?(@task_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] project_id Value to be assigned
    def project_id=(project_id)
      if project_id.nil?
        fail ArgumentError, 'project_id cannot be nil'
      end

      @project_id = project_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] task_type Object to be assigned
    def task_type=(task_type)
      validator = EnumAttributeValidator.new('String', ["brief", "create", "update", "pr_insights", "custom"])
      unless validator.valid?(task_type)
        fail ArgumentError, "invalid value for \"task_type\", must be one of #{validator.allowable_values}."
      end
      @task_type = task_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          project_id == o.project_id &&
          task_type == o.task_type &&
          prompt_id == o.prompt_id &&
          custom_topic == o.custom_topic &&
          user_instructions == o.user_instructions &&
          output_language_code == o.output_language_code &&
          existing_content == o.existing_content &&
          existing_content_url == o.existing_content_url
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [project_id, task_type, prompt_id, custom_topic, user_instructions, output_language_code, existing_content, existing_content_url].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
