=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.53.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class LocalBusiness < ApiModelBase
    # Stable grouping key: the lowercased name and address
    attr_accessor :business_key

    attr_accessor :title

    attr_accessor :address

    attr_accessor :domain

    attr_accessor :url

    attr_accessor :phone

    attr_accessor :avg_rating

    attr_accessor :reviews

    # Average rank of the business in the answer's list (1 = first)
    attr_accessor :avg_position

    attr_accessor :prompts

    attr_accessor :appearances

    attr_accessor :is_client

    attr_accessor :competitor_id

    attr_accessor :competitor_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'business_key' => :'business_key',
        :'title' => :'title',
        :'address' => :'address',
        :'domain' => :'domain',
        :'url' => :'url',
        :'phone' => :'phone',
        :'avg_rating' => :'avg_rating',
        :'reviews' => :'reviews',
        :'avg_position' => :'avg_position',
        :'prompts' => :'prompts',
        :'appearances' => :'appearances',
        :'is_client' => :'is_client',
        :'competitor_id' => :'competitor_id',
        :'competitor_name' => :'competitor_name'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'business_key' => :'String',
        :'title' => :'String',
        :'address' => :'String',
        :'domain' => :'String',
        :'url' => :'String',
        :'phone' => :'String',
        :'avg_rating' => :'Float',
        :'reviews' => :'Integer',
        :'avg_position' => :'Float',
        :'prompts' => :'Integer',
        :'appearances' => :'Integer',
        :'is_client' => :'Boolean',
        :'competitor_id' => :'Integer',
        :'competitor_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'address',
        :'domain',
        :'url',
        :'phone',
        :'avg_rating',
        :'reviews',
        :'avg_position',
        :'competitor_id',
        :'competitor_name'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::LocalBusiness` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::LocalBusiness`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'business_key')
        self.business_key = attributes[:'business_key']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'domain')
        self.domain = attributes[:'domain']
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'avg_rating')
        self.avg_rating = attributes[:'avg_rating']
      end

      if attributes.key?(:'reviews')
        self.reviews = attributes[:'reviews']
      end

      if attributes.key?(:'avg_position')
        self.avg_position = attributes[:'avg_position']
      end

      if attributes.key?(:'prompts')
        self.prompts = attributes[:'prompts']
      end

      if attributes.key?(:'appearances')
        self.appearances = attributes[:'appearances']
      end

      if attributes.key?(:'is_client')
        self.is_client = attributes[:'is_client']
      end

      if attributes.key?(:'competitor_id')
        self.competitor_id = attributes[:'competitor_id']
      end

      if attributes.key?(:'competitor_name')
        self.competitor_name = attributes[:'competitor_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          business_key == o.business_key &&
          title == o.title &&
          address == o.address &&
          domain == o.domain &&
          url == o.url &&
          phone == o.phone &&
          avg_rating == o.avg_rating &&
          reviews == o.reviews &&
          avg_position == o.avg_position &&
          prompts == o.prompts &&
          appearances == o.appearances &&
          is_client == o.is_client &&
          competitor_id == o.competitor_id &&
          competitor_name == o.competitor_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [business_key, title, address, domain, url, phone, avg_rating, reviews, avg_position, prompts, appearances, is_client, competitor_id, competitor_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
