=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.22.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class PromptSummaryRow < ApiModelBase
    attr_accessor :prompt_id

    attr_accessor :prompt_text

    # Only present when breakdown=model
    attr_accessor :model

    attr_accessor :responses

    attr_accessor :mentions

    attr_accessor :citations

    attr_accessor :visibility

    attr_accessor :mention_rate

    attr_accessor :citation_rate

    attr_accessor :avg_mention_position

    attr_accessor :avg_position

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'prompt_id' => :'prompt_id',
        :'prompt_text' => :'prompt_text',
        :'model' => :'model',
        :'responses' => :'responses',
        :'mentions' => :'mentions',
        :'citations' => :'citations',
        :'visibility' => :'visibility',
        :'mention_rate' => :'mention_rate',
        :'citation_rate' => :'citation_rate',
        :'avg_mention_position' => :'avg_mention_position',
        :'avg_position' => :'avg_position'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'prompt_id' => :'Integer',
        :'prompt_text' => :'String',
        :'model' => :'String',
        :'responses' => :'Integer',
        :'mentions' => :'Integer',
        :'citations' => :'Integer',
        :'visibility' => :'Float',
        :'mention_rate' => :'Float',
        :'citation_rate' => :'Float',
        :'avg_mention_position' => :'Float',
        :'avg_position' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'avg_mention_position',
        :'avg_position'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::PromptSummaryRow` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::PromptSummaryRow`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'prompt_id')
        self.prompt_id = attributes[:'prompt_id']
      end

      if attributes.key?(:'prompt_text')
        self.prompt_text = attributes[:'prompt_text']
      end

      if attributes.key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.key?(:'responses')
        self.responses = attributes[:'responses']
      end

      if attributes.key?(:'mentions')
        self.mentions = attributes[:'mentions']
      end

      if attributes.key?(:'citations')
        self.citations = attributes[:'citations']
      end

      if attributes.key?(:'visibility')
        self.visibility = attributes[:'visibility']
      end

      if attributes.key?(:'mention_rate')
        self.mention_rate = attributes[:'mention_rate']
      end

      if attributes.key?(:'citation_rate')
        self.citation_rate = attributes[:'citation_rate']
      end

      if attributes.key?(:'avg_mention_position')
        self.avg_mention_position = attributes[:'avg_mention_position']
      end

      if attributes.key?(:'avg_position')
        self.avg_position = attributes[:'avg_position']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          prompt_id == o.prompt_id &&
          prompt_text == o.prompt_text &&
          model == o.model &&
          responses == o.responses &&
          mentions == o.mentions &&
          citations == o.citations &&
          visibility == o.visibility &&
          mention_rate == o.mention_rate &&
          citation_rate == o.citation_rate &&
          avg_mention_position == o.avg_mention_position &&
          avg_position == o.avg_position
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [prompt_id, prompt_text, model, responses, mentions, citations, visibility, mention_rate, citation_rate, avg_mention_position, avg_position].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
