=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.57.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class PromptTagsAssignResponse < ApiModelBase
    attr_accessor :project_id

    # Prompts of the project among prompt_ids
    attr_accessor :prompts_targeted

    attr_accessor :tags_attached

    attr_accessor :new_links_created

    attr_accessor :skipped_already_linked

    # tag_names that matched no tag and were not created
    attr_accessor :missing_tag_names

    # prompt_ids that are not prompts of this project
    attr_accessor :ignored_prompt_ids

    attr_accessor :request_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'project_id' => :'project_id',
        :'prompts_targeted' => :'prompts_targeted',
        :'tags_attached' => :'tags_attached',
        :'new_links_created' => :'new_links_created',
        :'skipped_already_linked' => :'skipped_already_linked',
        :'missing_tag_names' => :'missing_tag_names',
        :'ignored_prompt_ids' => :'ignored_prompt_ids',
        :'request_id' => :'request_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'project_id' => :'Integer',
        :'prompts_targeted' => :'Integer',
        :'tags_attached' => :'Array<TagRef>',
        :'new_links_created' => :'Integer',
        :'skipped_already_linked' => :'Integer',
        :'missing_tag_names' => :'Array<String>',
        :'ignored_prompt_ids' => :'Array<Integer>',
        :'request_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::PromptTagsAssignResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::PromptTagsAssignResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      else
        self.project_id = nil
      end

      if attributes.key?(:'prompts_targeted')
        self.prompts_targeted = attributes[:'prompts_targeted']
      else
        self.prompts_targeted = nil
      end

      if attributes.key?(:'tags_attached')
        if (value = attributes[:'tags_attached']).is_a?(Array)
          self.tags_attached = value
        end
      else
        self.tags_attached = nil
      end

      if attributes.key?(:'new_links_created')
        self.new_links_created = attributes[:'new_links_created']
      else
        self.new_links_created = nil
      end

      if attributes.key?(:'skipped_already_linked')
        self.skipped_already_linked = attributes[:'skipped_already_linked']
      else
        self.skipped_already_linked = nil
      end

      if attributes.key?(:'missing_tag_names')
        if (value = attributes[:'missing_tag_names']).is_a?(Array)
          self.missing_tag_names = value
        end
      else
        self.missing_tag_names = nil
      end

      if attributes.key?(:'ignored_prompt_ids')
        if (value = attributes[:'ignored_prompt_ids']).is_a?(Array)
          self.ignored_prompt_ids = value
        end
      else
        self.ignored_prompt_ids = nil
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      else
        self.request_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @project_id.nil?
        invalid_properties.push('invalid value for "project_id", project_id cannot be nil.')
      end

      if @prompts_targeted.nil?
        invalid_properties.push('invalid value for "prompts_targeted", prompts_targeted cannot be nil.')
      end

      if @tags_attached.nil?
        invalid_properties.push('invalid value for "tags_attached", tags_attached cannot be nil.')
      end

      if @new_links_created.nil?
        invalid_properties.push('invalid value for "new_links_created", new_links_created cannot be nil.')
      end

      if @skipped_already_linked.nil?
        invalid_properties.push('invalid value for "skipped_already_linked", skipped_already_linked cannot be nil.')
      end

      if @missing_tag_names.nil?
        invalid_properties.push('invalid value for "missing_tag_names", missing_tag_names cannot be nil.')
      end

      if @ignored_prompt_ids.nil?
        invalid_properties.push('invalid value for "ignored_prompt_ids", ignored_prompt_ids cannot be nil.')
      end

      if @request_id.nil?
        invalid_properties.push('invalid value for "request_id", request_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @project_id.nil?
      return false if @prompts_targeted.nil?
      return false if @tags_attached.nil?
      return false if @new_links_created.nil?
      return false if @skipped_already_linked.nil?
      return false if @missing_tag_names.nil?
      return false if @ignored_prompt_ids.nil?
      return false if @request_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] project_id Value to be assigned
    def project_id=(project_id)
      if project_id.nil?
        fail ArgumentError, 'project_id cannot be nil'
      end

      @project_id = project_id
    end

    # Custom attribute writer method with validation
    # @param [Object] prompts_targeted Value to be assigned
    def prompts_targeted=(prompts_targeted)
      if prompts_targeted.nil?
        fail ArgumentError, 'prompts_targeted cannot be nil'
      end

      @prompts_targeted = prompts_targeted
    end

    # Custom attribute writer method with validation
    # @param [Object] tags_attached Value to be assigned
    def tags_attached=(tags_attached)
      if tags_attached.nil?
        fail ArgumentError, 'tags_attached cannot be nil'
      end

      @tags_attached = tags_attached
    end

    # Custom attribute writer method with validation
    # @param [Object] new_links_created Value to be assigned
    def new_links_created=(new_links_created)
      if new_links_created.nil?
        fail ArgumentError, 'new_links_created cannot be nil'
      end

      @new_links_created = new_links_created
    end

    # Custom attribute writer method with validation
    # @param [Object] skipped_already_linked Value to be assigned
    def skipped_already_linked=(skipped_already_linked)
      if skipped_already_linked.nil?
        fail ArgumentError, 'skipped_already_linked cannot be nil'
      end

      @skipped_already_linked = skipped_already_linked
    end

    # Custom attribute writer method with validation
    # @param [Object] missing_tag_names Value to be assigned
    def missing_tag_names=(missing_tag_names)
      if missing_tag_names.nil?
        fail ArgumentError, 'missing_tag_names cannot be nil'
      end

      @missing_tag_names = missing_tag_names
    end

    # Custom attribute writer method with validation
    # @param [Object] ignored_prompt_ids Value to be assigned
    def ignored_prompt_ids=(ignored_prompt_ids)
      if ignored_prompt_ids.nil?
        fail ArgumentError, 'ignored_prompt_ids cannot be nil'
      end

      @ignored_prompt_ids = ignored_prompt_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] request_id Value to be assigned
    def request_id=(request_id)
      if request_id.nil?
        fail ArgumentError, 'request_id cannot be nil'
      end

      @request_id = request_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          project_id == o.project_id &&
          prompts_targeted == o.prompts_targeted &&
          tags_attached == o.tags_attached &&
          new_links_created == o.new_links_created &&
          skipped_already_linked == o.skipped_already_linked &&
          missing_tag_names == o.missing_tag_names &&
          ignored_prompt_ids == o.ignored_prompt_ids &&
          request_id == o.request_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [project_id, prompts_targeted, tags_attached, new_links_created, skipped_already_linked, missing_tag_names, ignored_prompt_ids, request_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
