=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.48.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class UpdateProjectDraftRequest < ApiModelBase
    attr_accessor :step

    attr_accessor :name

    attr_accessor :brand_name

    attr_accessor :description

    attr_accessor :industry

    attr_accessor :matching_names

    attr_accessor :external_identifier

    attr_accessor :prompts

    attr_accessor :competitors

    attr_accessor :youtube_channel_url

    attr_accessor :instagram_profile_url

    attr_accessor :facebook_page_url

    attr_accessor :tiktok_profile_url

    attr_accessor :app_store_url

    attr_accessor :google_play_url

    attr_accessor :suggest

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'step' => :'step',
        :'name' => :'name',
        :'brand_name' => :'brand_name',
        :'description' => :'description',
        :'industry' => :'industry',
        :'matching_names' => :'matching_names',
        :'external_identifier' => :'external_identifier',
        :'prompts' => :'prompts',
        :'competitors' => :'competitors',
        :'youtube_channel_url' => :'youtube_channel_url',
        :'instagram_profile_url' => :'instagram_profile_url',
        :'facebook_page_url' => :'facebook_page_url',
        :'tiktok_profile_url' => :'tiktok_profile_url',
        :'app_store_url' => :'app_store_url',
        :'google_play_url' => :'google_play_url',
        :'suggest' => :'suggest'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'step' => :'String',
        :'name' => :'String',
        :'brand_name' => :'String',
        :'description' => :'String',
        :'industry' => :'Array<String>',
        :'matching_names' => :'Array<String>',
        :'external_identifier' => :'String',
        :'prompts' => :'Array<String>',
        :'competitors' => :'Array<Object>',
        :'youtube_channel_url' => :'String',
        :'instagram_profile_url' => :'String',
        :'facebook_page_url' => :'String',
        :'tiktok_profile_url' => :'String',
        :'app_store_url' => :'String',
        :'google_play_url' => :'String',
        :'suggest' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::UpdateProjectDraftRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::UpdateProjectDraftRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'step')
        self.step = attributes[:'step']
      else
        self.step = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'brand_name')
        self.brand_name = attributes[:'brand_name']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'industry')
        if (value = attributes[:'industry']).is_a?(Array)
          self.industry = value
        end
      end

      if attributes.key?(:'matching_names')
        if (value = attributes[:'matching_names']).is_a?(Array)
          self.matching_names = value
        end
      end

      if attributes.key?(:'external_identifier')
        self.external_identifier = attributes[:'external_identifier']
      end

      if attributes.key?(:'prompts')
        if (value = attributes[:'prompts']).is_a?(Array)
          self.prompts = value
        end
      end

      if attributes.key?(:'competitors')
        if (value = attributes[:'competitors']).is_a?(Array)
          self.competitors = value
        end
      end

      if attributes.key?(:'youtube_channel_url')
        self.youtube_channel_url = attributes[:'youtube_channel_url']
      end

      if attributes.key?(:'instagram_profile_url')
        self.instagram_profile_url = attributes[:'instagram_profile_url']
      end

      if attributes.key?(:'facebook_page_url')
        self.facebook_page_url = attributes[:'facebook_page_url']
      end

      if attributes.key?(:'tiktok_profile_url')
        self.tiktok_profile_url = attributes[:'tiktok_profile_url']
      end

      if attributes.key?(:'app_store_url')
        self.app_store_url = attributes[:'app_store_url']
      end

      if attributes.key?(:'google_play_url')
        self.google_play_url = attributes[:'google_play_url']
      end

      if attributes.key?(:'suggest')
        self.suggest = attributes[:'suggest']
      else
        self.suggest = true
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @step.nil?
        invalid_properties.push('invalid value for "step", step cannot be nil.')
      end

      if !@prompts.nil? && @prompts.length > 100
        invalid_properties.push('invalid value for "prompts", number of items must be less than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @step.nil?
      step_validator = EnumAttributeValidator.new('String', ["details", "prompts", "competitors", "owned_media"])
      return false unless step_validator.valid?(@step)
      return false if !@prompts.nil? && @prompts.length > 100
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] step Object to be assigned
    def step=(step)
      validator = EnumAttributeValidator.new('String', ["details", "prompts", "competitors", "owned_media"])
      unless validator.valid?(step)
        fail ArgumentError, "invalid value for \"step\", must be one of #{validator.allowable_values}."
      end
      @step = step
    end

    # Custom attribute writer method with validation
    # @param [Object] prompts Value to be assigned
    def prompts=(prompts)
      if prompts.nil?
        fail ArgumentError, 'prompts cannot be nil'
      end

      if prompts.length > 100
        fail ArgumentError, 'invalid value for "prompts", number of items must be less than or equal to 100.'
      end

      @prompts = prompts
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          step == o.step &&
          name == o.name &&
          brand_name == o.brand_name &&
          description == o.description &&
          industry == o.industry &&
          matching_names == o.matching_names &&
          external_identifier == o.external_identifier &&
          prompts == o.prompts &&
          competitors == o.competitors &&
          youtube_channel_url == o.youtube_channel_url &&
          instagram_profile_url == o.instagram_profile_url &&
          facebook_page_url == o.facebook_page_url &&
          tiktok_profile_url == o.tiktok_profile_url &&
          app_store_url == o.app_store_url &&
          google_play_url == o.google_play_url &&
          suggest == o.suggest
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [step, name, brand_name, description, industry, matching_names, external_identifier, prompts, competitors, youtube_channel_url, instagram_profile_url, facebook_page_url, tiktok_profile_url, app_store_url, google_play_url, suggest].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
