=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.57.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module LLMPulse
  class WebAnalyticsSchemaResponse < ApiModelBase
    attr_accessor :project_id

    # The connected web analytics provider.
    attr_accessor :provider

    # The property, site, report suite (rsid:...), data view (dataview:...) or project every query runs on.
    attr_accessor :property

    # The native query format the provider accepts.
    attr_accessor :query_language

    # The provider's reference for that format.
    attr_accessor :docs_url

    # Top-level query fields that are forwarded.
    attr_accessor :allowed_fields

    # What the bridge enforces and the provider's main constraints.
    attr_accessor :rules

    # A worked query to adapt.
    attr_accessor :example

    # The provider's live field list where it offers one: GA4 dimensions and metrics with custom definitions, Adobe ids, Matomo report methods, PostHog event names, the Plausible catalog. Null when the provider did not return it.
    attr_accessor :fields

    # Present when the field list could not be read; the format and example still apply.
    attr_accessor :fields_unavailable

    attr_accessor :request_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'project_id' => :'project_id',
        :'provider' => :'provider',
        :'property' => :'property',
        :'query_language' => :'query_language',
        :'docs_url' => :'docs_url',
        :'allowed_fields' => :'allowed_fields',
        :'rules' => :'rules',
        :'example' => :'example',
        :'fields' => :'fields',
        :'fields_unavailable' => :'fields_unavailable',
        :'request_id' => :'request_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'project_id' => :'Integer',
        :'provider' => :'String',
        :'property' => :'String',
        :'query_language' => :'String',
        :'docs_url' => :'String',
        :'allowed_fields' => :'Array<String>',
        :'rules' => :'Array<String>',
        :'example' => :'Hash<String, Object>',
        :'fields' => :'Hash<String, Object>',
        :'fields_unavailable' => :'String',
        :'request_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'fields',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LLMPulse::WebAnalyticsSchemaResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LLMPulse::WebAnalyticsSchemaResponse`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      end

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      end

      if attributes.key?(:'property')
        self.property = attributes[:'property']
      end

      if attributes.key?(:'query_language')
        self.query_language = attributes[:'query_language']
      end

      if attributes.key?(:'docs_url')
        self.docs_url = attributes[:'docs_url']
      end

      if attributes.key?(:'allowed_fields')
        if (value = attributes[:'allowed_fields']).is_a?(Array)
          self.allowed_fields = value
        end
      end

      if attributes.key?(:'rules')
        if (value = attributes[:'rules']).is_a?(Array)
          self.rules = value
        end
      end

      if attributes.key?(:'example')
        if (value = attributes[:'example']).is_a?(Hash)
          self.example = value
        end
      end

      if attributes.key?(:'fields')
        if (value = attributes[:'fields']).is_a?(Hash)
          self.fields = value
        end
      end

      if attributes.key?(:'fields_unavailable')
        self.fields_unavailable = attributes[:'fields_unavailable']
      end

      if attributes.key?(:'request_id')
        self.request_id = attributes[:'request_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      provider_validator = EnumAttributeValidator.new('String', ["google_analytics", "adobe_analytics", "matomo", "posthog", "plausible", "piano"])
      return false unless provider_validator.valid?(@provider)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] provider Object to be assigned
    def provider=(provider)
      validator = EnumAttributeValidator.new('String', ["google_analytics", "adobe_analytics", "matomo", "posthog", "plausible", "piano"])
      unless validator.valid?(provider)
        fail ArgumentError, "invalid value for \"provider\", must be one of #{validator.allowable_values}."
      end
      @provider = provider
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          project_id == o.project_id &&
          provider == o.provider &&
          property == o.property &&
          query_language == o.query_language &&
          docs_url == o.docs_url &&
          allowed_fields == o.allowed_fields &&
          rules == o.rules &&
          example == o.example &&
          fields == o.fields &&
          fields_unavailable == o.fields_unavailable &&
          request_id == o.request_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [project_id, provider, property, query_language, docs_url, allowed_fields, rules, example, fields, fields_unavailable, request_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
