=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.46.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

# Common files
require 'llmpulse/api_client'
require 'llmpulse/api_error'
require 'llmpulse/api_model_base'
require 'llmpulse/version'
require 'llmpulse/configuration'

# Models
require 'llmpulse/models/account_capacity'
require 'llmpulse/models/account_quota'
require 'llmpulse/models/actor'
require 'llmpulse/models/agent_bot'
require 'llmpulse/models/agent_bots_response'
require 'llmpulse/models/agent_traffic_response'
require 'llmpulse/models/answer_details'
require 'llmpulse/models/answer_details_locale'
require 'llmpulse/models/api_error'
require 'llmpulse/models/api_error_error'
require 'llmpulse/models/assign_prompt_tags_request'
require 'llmpulse/models/competitor'
require 'llmpulse/models/competitor_details'
require 'llmpulse/models/create_annotation_request'
require 'llmpulse/models/create_collection_request'
require 'llmpulse/models/create_competitor_request'
require 'llmpulse/models/create_project_draft_request'
require 'llmpulse/models/create_technical_geo_reports_request'
require 'llmpulse/models/create_webhook201_response'
require 'llmpulse/models/create_webhook_request'
require 'llmpulse/models/delete_webhook200_response'
require 'llmpulse/models/finalize_project_draft_request'
require 'llmpulse/models/get_account200_response'
require 'llmpulse/models/get_account200_response_limits'
require 'llmpulse/models/get_account200_response_rate_limits'
require 'llmpulse/models/get_account200_response_subscription'
require 'llmpulse/models/intelligence_task'
require 'llmpulse/models/intelligence_task_create_request'
require 'llmpulse/models/intelligence_task_update_request'
require 'llmpulse/models/intelligence_task_update_response'
require 'llmpulse/models/launch_recommendations_request'
require 'llmpulse/models/list_competitors200_response'
require 'llmpulse/models/list_projects200_response'
require 'llmpulse/models/list_webhooks200_response'
require 'llmpulse/models/list_webhooks200_response_data_inner'
require 'llmpulse/models/ping200_response'
require 'llmpulse/models/project'
require 'llmpulse/models/project_create_request'
require 'llmpulse/models/project_create_request_competitors_inner'
require 'llmpulse/models/project_create_request_owned_media'
require 'llmpulse/models/project_create_response'
require 'llmpulse/models/project_create_response_competitors'
require 'llmpulse/models/project_create_response_email_subscription'
require 'llmpulse/models/project_create_response_limits'
require 'llmpulse/models/project_create_response_prompts'
require 'llmpulse/models/project_details'
require 'llmpulse/models/project_details_all_of_stats'
require 'llmpulse/models/prompt_summary_response'
require 'llmpulse/models/prompt_summary_row'
require 'llmpulse/models/prompts_create_request'
require 'llmpulse/models/prompts_create_response'
require 'llmpulse/models/prompts_create_response_data_inner'
require 'llmpulse/models/sample_webhook_payloads200_response'
require 'llmpulse/models/sample_webhook_payloads200_response_data_inner'
require 'llmpulse/models/search_console_filters_inner'
require 'llmpulse/models/sov_response'
require 'llmpulse/models/sov_response_breakdown_inner'
require 'llmpulse/models/sov_response_current_inner'
require 'llmpulse/models/sov_response_over_time_inner'
require 'llmpulse/models/sov_response_periods_inner'
require 'llmpulse/models/summary_response'
require 'llmpulse/models/summary_response_all_of_position_distribution'
require 'llmpulse/models/summary_response_all_of_summary_value_inner'
require 'llmpulse/models/timeseries_point'
require 'llmpulse/models/timeseries_response'
require 'llmpulse/models/timeseries_series'
require 'llmpulse/models/top_sources_response'
require 'llmpulse/models/top_sources_response_data_inner'
require 'llmpulse/models/update_annotation_request'
require 'llmpulse/models/update_collection_request'
require 'llmpulse/models/update_competitor_request'
require 'llmpulse/models/update_project_draft_request'
require 'llmpulse/models/update_project_request'

# APIs
require 'llmpulse/api/ai_agent_traffic_api'
require 'llmpulse/api/ai_model_insights_api'
require 'llmpulse/api/account_api'
require 'llmpulse/api/annotations_api'
require 'llmpulse/api/answers_api'
require 'llmpulse/api/collections_tags_api'
require 'llmpulse/api/competitors_api'
require 'llmpulse/api/geo_writer_api'
require 'llmpulse/api/health_api'
require 'llmpulse/api/mentions_citations_api'
require 'llmpulse/api/metrics_api'
require 'llmpulse/api/owned_media_communities_api'
require 'llmpulse/api/projects_api'
require 'llmpulse/api/prompts_api'
require 'llmpulse/api/recommendations_api'
require 'llmpulse/api/reputation_studies_api'
require 'llmpulse/api/search_console_api'
require 'llmpulse/api/sentiments_api'
require 'llmpulse/api/shopping_ads_api'
require 'llmpulse/api/sources_citation_intelligence_api'
require 'llmpulse/api/technical_geo_reports_api'
require 'llmpulse/api/webhooks_api'

module LLMPulse
  class << self
    # Customize default settings for the SDK using block.
    #   LLMPulse.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
