=begin
#LLM Pulse API

#REST API client for LLM Pulse AI visibility analytics.

The version of the OpenAPI document: 1.46.0
Contact: info@llmpulse.ai
Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'cgi'

module LLMPulse
  class MentionsCitationsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List all citations (brand + competitor)
    # Unified citations stream with an `actor_type` field on each record. Includes visible citations and background source references; background references use position 0, meaning no visible rank.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [nil]
    def list_all_citations(project_id, opts = {})
      list_all_citations_with_http_info(project_id, opts)
      nil
    end

    # List all citations (brand + competitor)
    # Unified citations stream with an &#x60;actor_type&#x60; field on each record. Includes visible citations and background source references; background references use position 0, meaning no visible rank.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_all_citations_with_http_info(project_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MentionsCitationsApi.list_all_citations ...'
      end
      # verify the required parameter 'project_id' is set
      if @api_client.config.client_side_validation && project_id.nil?
        fail ArgumentError, "Missing the required parameter 'project_id' when calling MentionsCitationsApi.list_all_citations"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling MentionsCitationsApi.list_all_citations, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_all_citations, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_all_citations, must be greater than or equal to 1.'
      end

      allowable_values = ["chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"]
      if @api_client.config.client_side_validation && opts[:'model'] && !allowable_values.include?(opts[:'model'])
        fail ArgumentError, "invalid value for \"model\", must be one of #{allowable_values}"
      end
      pattern = Regexp.new(/^\d+(,\d+)*$/)
      if @api_client.config.client_side_validation && !opts[:'collection_id'].nil? && opts[:'collection_id'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"collection_id\"]' when calling MentionsCitationsApi.list_all_citations, must conform to the pattern #{pattern}."
      end

      allowable_values = ["flat", "csv"]
      if @api_client.config.client_side_validation && opts[:'output'] && !allowable_values.include?(opts[:'output'])
        fail ArgumentError, "invalid value for \"output\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/dimensions/all_citations'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'project_id'] = project_id
      query_params[:'competitors'] = opts[:'competitors'] if !opts[:'competitors'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'collection_id'] = opts[:'collection_id'] if !opts[:'collection_id'].nil?
      query_params[:'prompt'] = opts[:'prompt'] if !opts[:'prompt'].nil?
      query_params[:'from'] = opts[:'from'] if !opts[:'from'].nil?
      query_params[:'to'] = opts[:'to'] if !opts[:'to'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?

      # header parameters
      header_params = opts[:header_params] || {}

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"MentionsCitationsApi.list_all_citations",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MentionsCitationsApi#list_all_citations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List all mentions (brand + competitor)
    # Unified mentions stream. Each record has an `actor_type` field (`project` or `competitor`) so the same payload covers both.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [nil]
    def list_all_mentions(project_id, opts = {})
      list_all_mentions_with_http_info(project_id, opts)
      nil
    end

    # List all mentions (brand + competitor)
    # Unified mentions stream. Each record has an &#x60;actor_type&#x60; field (&#x60;project&#x60; or &#x60;competitor&#x60;) so the same payload covers both.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_all_mentions_with_http_info(project_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MentionsCitationsApi.list_all_mentions ...'
      end
      # verify the required parameter 'project_id' is set
      if @api_client.config.client_side_validation && project_id.nil?
        fail ArgumentError, "Missing the required parameter 'project_id' when calling MentionsCitationsApi.list_all_mentions"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling MentionsCitationsApi.list_all_mentions, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_all_mentions, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_all_mentions, must be greater than or equal to 1.'
      end

      allowable_values = ["chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"]
      if @api_client.config.client_side_validation && opts[:'model'] && !allowable_values.include?(opts[:'model'])
        fail ArgumentError, "invalid value for \"model\", must be one of #{allowable_values}"
      end
      pattern = Regexp.new(/^\d+(,\d+)*$/)
      if @api_client.config.client_side_validation && !opts[:'collection_id'].nil? && opts[:'collection_id'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"collection_id\"]' when calling MentionsCitationsApi.list_all_mentions, must conform to the pattern #{pattern}."
      end

      allowable_values = ["flat", "csv"]
      if @api_client.config.client_side_validation && opts[:'output'] && !allowable_values.include?(opts[:'output'])
        fail ArgumentError, "invalid value for \"output\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/dimensions/all_mentions'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'project_id'] = project_id
      query_params[:'competitors'] = opts[:'competitors'] if !opts[:'competitors'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'collection_id'] = opts[:'collection_id'] if !opts[:'collection_id'].nil?
      query_params[:'prompt'] = opts[:'prompt'] if !opts[:'prompt'].nil?
      query_params[:'from'] = opts[:'from'] if !opts[:'from'].nil?
      query_params[:'to'] = opts[:'to'] if !opts[:'to'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?

      # header parameters
      header_params = opts[:header_params] || {}

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"MentionsCitationsApi.list_all_mentions",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MentionsCitationsApi#list_all_mentions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List brand citations
    # Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [String] :country_code One ISO country code or a comma-separated list (e.g. US,GB,DE)
    # @option opts [String] :language_code One ISO language code or a comma-separated list (e.g. en,es,de)
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [nil]
    def list_citations(project_id, opts = {})
      list_citations_with_http_info(project_id, opts)
      nil
    end

    # List brand citations
    # Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [String] :country_code One ISO country code or a comma-separated list (e.g. US,GB,DE)
    # @option opts [String] :language_code One ISO language code or a comma-separated list (e.g. en,es,de)
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_citations_with_http_info(project_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MentionsCitationsApi.list_citations ...'
      end
      # verify the required parameter 'project_id' is set
      if @api_client.config.client_side_validation && project_id.nil?
        fail ArgumentError, "Missing the required parameter 'project_id' when calling MentionsCitationsApi.list_citations"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling MentionsCitationsApi.list_citations, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_citations, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_citations, must be greater than or equal to 1.'
      end

      allowable_values = ["chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"]
      if @api_client.config.client_side_validation && opts[:'model'] && !allowable_values.include?(opts[:'model'])
        fail ArgumentError, "invalid value for \"model\", must be one of #{allowable_values}"
      end
      pattern = Regexp.new(/^\d+(,\d+)*$/)
      if @api_client.config.client_side_validation && !opts[:'collection_id'].nil? && opts[:'collection_id'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"collection_id\"]' when calling MentionsCitationsApi.list_citations, must conform to the pattern #{pattern}."
      end

      allowable_values = ["flat", "csv"]
      if @api_client.config.client_side_validation && opts[:'output'] && !allowable_values.include?(opts[:'output'])
        fail ArgumentError, "invalid value for \"output\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/dimensions/citations'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'project_id'] = project_id
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'collection_id'] = opts[:'collection_id'] if !opts[:'collection_id'].nil?
      query_params[:'country_code'] = opts[:'country_code'] if !opts[:'country_code'].nil?
      query_params[:'language_code'] = opts[:'language_code'] if !opts[:'language_code'].nil?
      query_params[:'prompt'] = opts[:'prompt'] if !opts[:'prompt'].nil?
      query_params[:'from'] = opts[:'from'] if !opts[:'from'].nil?
      query_params[:'to'] = opts[:'to'] if !opts[:'to'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?

      # header parameters
      header_params = opts[:header_params] || {}

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"MentionsCitationsApi.list_citations",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MentionsCitationsApi#list_citations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List competitor citations
    # Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [nil]
    def list_competitor_citations(project_id, opts = {})
      list_competitor_citations_with_http_info(project_id, opts)
      nil
    end

    # List competitor citations
    # Includes visible citations and background source references. Background references use position 0, meaning no visible rank.
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_competitor_citations_with_http_info(project_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MentionsCitationsApi.list_competitor_citations ...'
      end
      # verify the required parameter 'project_id' is set
      if @api_client.config.client_side_validation && project_id.nil?
        fail ArgumentError, "Missing the required parameter 'project_id' when calling MentionsCitationsApi.list_competitor_citations"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling MentionsCitationsApi.list_competitor_citations, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_competitor_citations, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_competitor_citations, must be greater than or equal to 1.'
      end

      allowable_values = ["chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"]
      if @api_client.config.client_side_validation && opts[:'model'] && !allowable_values.include?(opts[:'model'])
        fail ArgumentError, "invalid value for \"model\", must be one of #{allowable_values}"
      end
      pattern = Regexp.new(/^\d+(,\d+)*$/)
      if @api_client.config.client_side_validation && !opts[:'collection_id'].nil? && opts[:'collection_id'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"collection_id\"]' when calling MentionsCitationsApi.list_competitor_citations, must conform to the pattern #{pattern}."
      end

      allowable_values = ["flat", "csv"]
      if @api_client.config.client_side_validation && opts[:'output'] && !allowable_values.include?(opts[:'output'])
        fail ArgumentError, "invalid value for \"output\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/dimensions/competitor_citations'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'project_id'] = project_id
      query_params[:'competitors'] = opts[:'competitors'] if !opts[:'competitors'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'collection_id'] = opts[:'collection_id'] if !opts[:'collection_id'].nil?
      query_params[:'prompt'] = opts[:'prompt'] if !opts[:'prompt'].nil?
      query_params[:'from'] = opts[:'from'] if !opts[:'from'].nil?
      query_params[:'to'] = opts[:'to'] if !opts[:'to'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?

      # header parameters
      header_params = opts[:header_params] || {}

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"MentionsCitationsApi.list_competitor_citations",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MentionsCitationsApi#list_competitor_citations\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List competitor mentions
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [nil]
    def list_competitor_mentions(project_id, opts = {})
      list_competitor_mentions_with_http_info(project_id, opts)
      nil
    end

    # List competitor mentions
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [String] :competitors Comma-separated competitor IDs (unknown IDs return ERR_INVALID_PARAM)
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_competitor_mentions_with_http_info(project_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MentionsCitationsApi.list_competitor_mentions ...'
      end
      # verify the required parameter 'project_id' is set
      if @api_client.config.client_side_validation && project_id.nil?
        fail ArgumentError, "Missing the required parameter 'project_id' when calling MentionsCitationsApi.list_competitor_mentions"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling MentionsCitationsApi.list_competitor_mentions, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_competitor_mentions, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_competitor_mentions, must be greater than or equal to 1.'
      end

      allowable_values = ["chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"]
      if @api_client.config.client_side_validation && opts[:'model'] && !allowable_values.include?(opts[:'model'])
        fail ArgumentError, "invalid value for \"model\", must be one of #{allowable_values}"
      end
      pattern = Regexp.new(/^\d+(,\d+)*$/)
      if @api_client.config.client_side_validation && !opts[:'collection_id'].nil? && opts[:'collection_id'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"collection_id\"]' when calling MentionsCitationsApi.list_competitor_mentions, must conform to the pattern #{pattern}."
      end

      allowable_values = ["flat", "csv"]
      if @api_client.config.client_side_validation && opts[:'output'] && !allowable_values.include?(opts[:'output'])
        fail ArgumentError, "invalid value for \"output\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/dimensions/competitor_mentions'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'project_id'] = project_id
      query_params[:'competitors'] = opts[:'competitors'] if !opts[:'competitors'].nil?
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'collection_id'] = opts[:'collection_id'] if !opts[:'collection_id'].nil?
      query_params[:'prompt'] = opts[:'prompt'] if !opts[:'prompt'].nil?
      query_params[:'from'] = opts[:'from'] if !opts[:'from'].nil?
      query_params[:'to'] = opts[:'to'] if !opts[:'to'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?

      # header parameters
      header_params = opts[:header_params] || {}

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"MentionsCitationsApi.list_competitor_mentions",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MentionsCitationsApi#list_competitor_mentions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # List brand mentions
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [String] :country_code One ISO country code or a comma-separated list (e.g. US,GB,DE)
    # @option opts [String] :language_code One ISO language code or a comma-separated list (e.g. en,es,de)
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [nil]
    def list_mentions(project_id, opts = {})
      list_mentions_with_http_info(project_id, opts)
      nil
    end

    # List brand mentions
    # @param project_id [Integer] Project ID
    # @param [Hash] opts the optional parameters
    # @option opts [Integer] :page  (default to 1)
    # @option opts [Integer] :per_page  (default to 20)
    # @option opts [String] :model Filter by AI model. Models the API key&#39;s user has not enabled are silently dropped.
    # @option opts [String] :collection_id One collection/tag ID or a comma-separated list of IDs. A query value is always a string on the wire, so it is typed as one: the previous integer-or-string union made generators emit a wrapper type they could not serialize.
    # @option opts [String] :country_code One ISO country code or a comma-separated list (e.g. US,GB,DE)
    # @option opts [String] :language_code One ISO language code or a comma-separated list (e.g. en,es,de)
    # @option opts [Integer] :prompt Filter by prompt ID
    # @option opts [Time] :from 
    # @option opts [Time] :to End of the window. A date-only value such as 2026-09-01 covers that whole day. Pass a full timestamp to end the window earlier.
    # @option opts [String] :output Rectangular output for BI tools (Tableau, Excel, Sheets, ELT). Omit for the default nested JSON. &#39;flat&#39; returns the same metadata plus &#39;columns&#39; and &#39;rows&#39;; &#39;csv&#39; returns those rows as text/csv. Errors are always returned as JSON.
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def list_mentions_with_http_info(project_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MentionsCitationsApi.list_mentions ...'
      end
      # verify the required parameter 'project_id' is set
      if @api_client.config.client_side_validation && project_id.nil?
        fail ArgumentError, "Missing the required parameter 'project_id' when calling MentionsCitationsApi.list_mentions"
      end
      if @api_client.config.client_side_validation && !opts[:'page'].nil? && opts[:'page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"page"]" when calling MentionsCitationsApi.list_mentions, must be greater than or equal to 1.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] > 100
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_mentions, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'per_page'].nil? && opts[:'per_page'] < 1
        fail ArgumentError, 'invalid value for "opts[:"per_page"]" when calling MentionsCitationsApi.list_mentions, must be greater than or equal to 1.'
      end

      allowable_values = ["chatgpt", "perplexity", "gemini", "ai_overview", "ai_mode", "copilot", "claude", "grok", "deepseek", "meta_ai", "amazon_rufus", "naver_ai", "baidu_ai"]
      if @api_client.config.client_side_validation && opts[:'model'] && !allowable_values.include?(opts[:'model'])
        fail ArgumentError, "invalid value for \"model\", must be one of #{allowable_values}"
      end
      pattern = Regexp.new(/^\d+(,\d+)*$/)
      if @api_client.config.client_side_validation && !opts[:'collection_id'].nil? && opts[:'collection_id'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"collection_id\"]' when calling MentionsCitationsApi.list_mentions, must conform to the pattern #{pattern}."
      end

      allowable_values = ["flat", "csv"]
      if @api_client.config.client_side_validation && opts[:'output'] && !allowable_values.include?(opts[:'output'])
        fail ArgumentError, "invalid value for \"output\", must be one of #{allowable_values}"
      end
      # resource path
      local_var_path = '/dimensions/mentions'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'project_id'] = project_id
      query_params[:'page'] = opts[:'page'] if !opts[:'page'].nil?
      query_params[:'per_page'] = opts[:'per_page'] if !opts[:'per_page'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'collection_id'] = opts[:'collection_id'] if !opts[:'collection_id'].nil?
      query_params[:'country_code'] = opts[:'country_code'] if !opts[:'country_code'].nil?
      query_params[:'language_code'] = opts[:'language_code'] if !opts[:'language_code'].nil?
      query_params[:'prompt'] = opts[:'prompt'] if !opts[:'prompt'].nil?
      query_params[:'from'] = opts[:'from'] if !opts[:'from'].nil?
      query_params[:'to'] = opts[:'to'] if !opts[:'to'].nil?
      query_params[:'output'] = opts[:'output'] if !opts[:'output'].nil?

      # header parameters
      header_params = opts[:header_params] || {}

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['BearerAuth']

      new_options = opts.merge(
        :operation => :"MentionsCitationsApi.list_mentions",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MentionsCitationsApi#list_mentions\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
